import type { Transformation } from './types.js';

/**
 * Complete Base120 Mental Models Dataset
 * All 120 mental models across 6 transformations
 * Source: https://github.com/hummbl-dev/mcp-server
 */
export const TRANSFORMATIONS: Record<string, Transformation> = {
  P: {
    code: 'P',
    name: 'Perspective',
    description: 'Frame and name what is. Anchor or shift point of view.',
    models: [
      {
        code: 'P1',
        name: 'First Principles Framing',
        transformation: 'P',
        definition: 'Reduce complex problems to foundational truths that cannot be further simplified',
        priority: 1,
        whenToUse: 'When solving new problems where analogy might mislead',
        example: 'Elon Musk reasoning about battery costs by raw material prices rather than market history'
      },
      {
        code: 'P2',
        name: 'Stakeholder Mapping',
        transformation: 'P',
        definition: 'Identify all parties with interest, influence, or impact in a system or decision',
        priority: 1,
        whenToUse: 'When launching a product or changing a policy',
        example: 'Mapping users, buyers, regulators, and internal teams for a software launch'
      },
      {
        code: 'P3',
        name: 'Identity Stack',
        transformation: 'P',
        definition: 'Recognize that individuals operate from multiple nested identities simultaneously',
        priority: 2,
        whenToUse: 'When understanding user motivations or organizational behavior',
      },
      {
        code: 'P4',
        name: 'Lens Shifting',
        transformation: 'P',
        definition: 'Deliberately adopt different interpretive frameworks to reveal hidden aspects',
        priority: 1,
        whenToUse: 'When stuck in one way of viewing a problem',
      },
      {
        code: 'P5',
        name: 'Empathy Mapping',
        transformation: 'P',
        definition: 'Systematically capture what stakeholders see, think, feel, and do in their context',
        priority: 2,
        whenToUse: 'During user research or product design',
      },
      {
        code: 'P6',
        name: 'Point-of-View Anchoring',
        transformation: 'P',
        definition: 'Establish and maintain a consistent reference frame before analysis begins',
        priority: 3,
        whenToUse: 'Before complex analysis or decision-making',
      },
      {
        code: 'P7',
        name: 'Perspective Switching',
        transformation: 'P',
        definition: 'Rotate through multiple viewpoints to identify invariants and blind spots',
        priority: 2,
        whenToUse: 'When seeking comprehensive understanding',
      },
      {
        code: 'P8',
        name: 'Narrative Framing',
        transformation: 'P',
        definition: 'Structure information as causal stories with conflict, choice, and consequence',
        priority: 3,
        whenToUse: 'When communicating complex ideas or strategies',
      },
      {
        code: 'P9',
        name: 'Cultural Lens Shifting',
        transformation: 'P',
        definition: 'Adjust communication and interpretation for different cultural contexts and norms',
        priority: 4,
        whenToUse: 'In cross-cultural or international contexts',
      },
      {
        code: 'P10',
        name: 'Context Windowing',
        transformation: 'P',
        definition: 'Define explicit boundaries in time, space, and scope for analysis or action',
        priority: 2,
        whenToUse: 'When scoping a project or analysis',
      },
      {
        code: 'P11',
        name: 'Role Perspective-Taking',
        transformation: 'P',
        definition: 'Temporarily inhabit specific roles to understand constraints and priorities',
        priority: 3,
        whenToUse: 'When designing systems or processes for others',
      },
      {
        code: 'P12',
        name: 'Temporal Framing',
        transformation: 'P',
        definition: 'Organize understanding across past causes, present states, and future implications',
        priority: 3,
        whenToUse: 'For strategic planning or historical analysis',
      },
      {
        code: 'P13',
        name: 'Spatial Framing',
        transformation: 'P',
        definition: 'Scale perspective from local details to global patterns and back',
        priority: 4,
        whenToUse: 'When dealing with multi-scale systems',
      },
      {
        code: 'P14',
        name: 'Reference Class Framing',
        transformation: 'P',
        definition: 'Select comparable situations to inform judgment and avoid uniqueness bias',
        priority: 3,
        whenToUse: 'When forecasting or estimating',
      },
      {
        code: 'P15',
        name: 'Assumption Surfacing',
        transformation: 'P',
        definition: 'Explicitly identify and document beliefs underlying plans or models',
        priority: 2,
        whenToUse: 'Before major decisions or commitments',
      },
      {
        code: 'P16',
        name: 'Identity-Context Reciprocity',
        transformation: 'P',
        definition: 'Recognize how identities shape interpretations and contexts reinforce identities',
        priority: 5,
        whenToUse: 'In organizational change or culture work',
      },
      {
        code: 'P17',
        name: 'Frame Control & Reframing',
        transformation: 'P',
        definition: 'Consciously select or reshape interpretive frames to enable new solutions',
        priority: 2,
        whenToUse: 'When traditional approaches fail',
      },
      {
        code: 'P18',
        name: 'Boundary Object Selection',
        transformation: 'P',
        definition: 'Choose representations that bridge multiple perspectives while remaining meaningful',
        priority: 4,
        whenToUse: 'In cross-functional collaboration',
      },
      {
        code: 'P19',
        name: 'Sensemaking Canvases',
        transformation: 'P',
        definition: 'Deploy structured templates to systematically capture and organize observations',
        priority: 3,
        whenToUse: 'During discovery or research phases',
      },
      {
        code: 'P20',
        name: 'Worldview Articulation',
        transformation: 'P',
        definition: 'Make explicit the fundamental beliefs and values that drive interpretation and action',
        priority: 4,
        whenToUse: 'For deep organizational or personal alignment',
      },
    ],
  },
  IN: {
    code: 'IN',
    name: 'Inversion',
    description: 'Reverse assumptions. Examine opposites, edges, negations.',
    models: [
      {
        code: 'IN1',
        name: 'Subtractive Thinking',
        transformation: 'IN',
        definition: 'Improve systems by removing elements rather than adding complexity',
        priority: 1,
        whenToUse: 'When a system is sluggish or over-complicated',
        example: 'Removing meetings to improve productivity instead of adding coordination tools'
      },
      {
        code: 'IN2',
        name: 'Premortem Analysis',
        transformation: 'IN',
        definition: 'Assume failure has occurred and work backward to identify causes',
        priority: 1,
        whenToUse: 'Before launching major initiatives',
      },
      {
        code: 'IN3',
        name: 'Problem Reversal',
        transformation: 'IN',
        definition: 'Solve the inverse of the stated problem to reveal insights',
        priority: 2,
        whenToUse: 'When direct approaches seem blocked',
      },
      {
        code: 'IN4',
        name: 'Contra-Logic',
        transformation: 'IN',
        definition: 'Argue the opposite position to stress-test assumptions and expose weak reasoning',
        priority: 2,
        whenToUse: 'During strategic planning or critical decisions',
      },
      {
        code: 'IN5',
        name: 'Negative Space Framing',
        transformation: 'IN',
        definition: 'Study what is absent rather than what is present',
        priority: 3,
        whenToUse: 'When analyzing opportunities or gaps',
      },
      {
        code: 'IN6',
        name: 'Inverse/Proof by Contradiction',
        transformation: 'IN',
        definition: 'Assume a claim is false, derive logical impossibility, thus proving the claim true',
        priority: 3,
        whenToUse: 'For rigorous logical validation',
      },
      {
        code: 'IN7',
        name: 'Boundary Testing',
        transformation: 'IN',
        definition: 'Explore extreme conditions to find system limits and breaking points',
        priority: 2,
        whenToUse: 'During system design or testing',
      },
      {
        code: 'IN8',
        name: 'Contrapositive Reasoning',
        transformation: 'IN',
        definition: 'Use logical equivalence that if A then B equals if not B then not A',
        priority: 4,
        whenToUse: 'In formal logic or argumentation',
      },
      {
        code: 'IN9',
        name: 'Backward Induction',
        transformation: 'IN',
        definition: 'Begin with desired end state and work backward to determine necessary steps',
        priority: 2,
        whenToUse: 'For project planning or goal achievement',
      },
      {
        code: 'IN10',
        name: 'Red Teaming',
        transformation: 'IN',
        definition: 'Organize adversarial review to find vulnerabilities through simulated attack',
        priority: 2,
        whenToUse: 'For security or resilience testing',
      },
      {
        code: 'IN11',
        name: "Devil's Advocate Protocol",
        transformation: 'IN',
        definition: 'Assign explicit role to argue against group consensus or preferred option',
        priority: 3,
        whenToUse: 'To avoid groupthink',
      },
      {
        code: 'IN12',
        name: 'Failure First Design',
        transformation: 'IN',
        definition: 'Begin planning by identifying all possible failure modes and designing to prevent them',
        priority: 3,
        whenToUse: 'For safety-critical systems',
      },
      {
        code: 'IN13',
        name: 'Opportunity Cost Focus',
        transformation: 'IN',
        definition: 'Evaluate options by what must be forgone rather than what is gained',
        priority: 2,
        whenToUse: 'When making resource allocation decisions',
      },
      {
        code: 'IN14',
        name: 'Second-Order Effects (Inverted)',
        transformation: 'IN',
        definition: 'Trace negative downstream consequences rather than immediate benefits',
        priority: 3,
        whenToUse: 'For risk analysis',
      },
      {
        code: 'IN15',
        name: 'Constraint Reversal',
        transformation: 'IN',
        definition: 'Temporarily remove assumed constraints to explore alternative solution space',
        priority: 2,
        whenToUse: 'When conventional solutions fail',
      },
      {
        code: 'IN16',
        name: 'Inverse Optimization',
        transformation: 'IN',
        definition: 'Maximize worst outcomes to understand system vulnerabilities',
        priority: 4,
        whenToUse: 'For stress testing or robustness analysis',
      },
      {
        code: 'IN17',
        name: 'Counterfactual Negation',
        transformation: 'IN',
        definition: 'Imagine outcomes if key decision had been reversed',
        priority: 4,
        whenToUse: 'For learning from decisions',
      },
      {
        code: 'IN18',
        name: 'Kill-Criteria & Stop Rules',
        transformation: 'IN',
        definition: 'Define conditions that trigger project termination before launch',
        priority: 3,
        whenToUse: 'At project inception',
      },
      {
        code: 'IN19',
        name: 'Harm Minimization (Via Negativa)',
        transformation: 'IN',
        definition: 'Improve by removing harmful elements rather than adding beneficial ones',
        priority: 3,
        whenToUse: 'For health, safety, or simplification',
      },
      {
        code: 'IN20',
        name: 'Antigoals & Anti-Patterns Catalog',
        transformation: 'IN',
        definition: 'Document failure modes to avoid rather than success patterns to emulate',
        priority: 4,
        whenToUse: 'For organizational learning',
      },
    ],
  },
  CO: {
    code: 'CO',
    name: 'Composition',
    description: 'Combine parts into coherent wholes.',
    models: [
      {
        code: 'CO1',
        name: 'Synergy Principle',
        transformation: 'CO',
        definition: 'Design combinations where integrated value exceeds sum of parts',
        priority: 1,
        whenToUse: 'When assembling teams or systems',
      },
      {
        code: 'CO2',
        name: 'Chunking',
        transformation: 'CO',
        definition: 'Group related elements into meaningful units to reduce cognitive load',
        priority: 1,
        whenToUse: 'When organizing information or tasks',
      },
      {
        code: 'CO3',
        name: 'Functional Composition',
        transformation: 'CO',
        definition: 'Chain pure operations where output of one becomes input of next',
        priority: 2,
        whenToUse: 'In programming or process design',
      },
      {
        code: 'CO4',
        name: 'Interdisciplinary Synthesis',
        transformation: 'CO',
        definition: 'Merge insights from distinct fields to generate novel solutions',
        priority: 2,
        whenToUse: 'For innovation or complex problem-solving',
      },
      {
        code: 'CO5',
        name: 'Emergence',
        transformation: 'CO',
        definition: 'Recognize higher-order behavior arising from component interactions',
        priority: 2,
        whenToUse: 'When studying complex systems',
      },
      {
        code: 'CO6',
        name: 'Gestalt Integration',
        transformation: 'CO',
        definition: 'Perceive and leverage whole patterns rather than isolated components',
        priority: 3,
        whenToUse: 'In design or pattern recognition',
      },
      {
        code: 'CO7',
        name: 'Network Effects',
        transformation: 'CO',
        definition: 'Exploit increasing value as user base or connections grow',
        priority: 2,
        whenToUse: 'For platform or network businesses',
      },
      {
        code: 'CO8',
        name: 'Layered Abstraction',
        transformation: 'CO',
        definition: 'Separate concerns into hierarchical levels with clear interfaces between them',
        priority: 2,
        whenToUse: 'In software architecture or system design',
      },
      {
        code: 'CO9',
        name: 'Interface Contracts',
        transformation: 'CO',
        definition: 'Define explicit agreements about data structures and behavior between components',
        priority: 3,
        whenToUse: 'For API design or team coordination',
      },
      {
        code: 'CO10',
        name: 'Pipeline Orchestration',
        transformation: 'CO',
        definition: 'Coordinate sequential stages with explicit handoffs and error handling',
        priority: 3,
        whenToUse: 'For workflow or data pipeline design',
      },
      {
        code: 'CO11',
        name: 'Pattern Composition (Tiling)',
        transformation: 'CO',
        definition: 'Combine repeating elements to construct complex structures efficiently',
        priority: 4,
        whenToUse: 'In architecture or generative design',
      },
      {
        code: 'CO12',
        name: 'Modular Interoperability',
        transformation: 'CO',
        definition: 'Ensure independent components work together through standardized connections',
        priority: 3,
        whenToUse: 'For plugin systems or microservices',
      },
      {
        code: 'CO13',
        name: 'Cross-Domain Analogy',
        transformation: 'CO',
        definition: 'Transfer solution patterns from one domain to solve problems in another',
        priority: 2,
        whenToUse: 'For creative problem-solving',
      },
      {
        code: 'CO14',
        name: 'Platformization',
        transformation: 'CO',
        definition: 'Extract common capabilities into reusable infrastructure serving multiple use cases',
        priority: 3,
        whenToUse: 'When building scalable systems',
      },
      {
        code: 'CO15',
        name: 'Combinatorial Design',
        transformation: 'CO',
        definition: 'Systematically explore option combinations to find optimal configurations',
        priority: 4,
        whenToUse: 'For optimization or experimentation',
      },
      {
        code: 'CO16',
        name: 'System Integration Testing',
        transformation: 'CO',
        definition: 'Verify assembled components work correctly together, not just in isolation',
        priority: 3,
        whenToUse: 'During quality assurance',
      },
      {
        code: 'CO17',
        name: 'Orchestration vs Choreography',
        transformation: 'CO',
        definition: 'Choose between centralized coordination or distributed peer-to-peer interaction',
        priority: 4,
        whenToUse: 'For distributed system design',
      },
      {
        code: 'CO18',
        name: 'Knowledge Graphing',
        transformation: 'CO',
        definition: 'Represent information as interconnected entities and relationships',
        priority: 3,
        whenToUse: 'For knowledge management',
      },
      {
        code: 'CO19',
        name: 'Multi-Modal Integration',
        transformation: 'CO',
        definition: 'Synthesize information from different sensory or data modalities',
        priority: 4,
        whenToUse: 'For rich user experiences or AI systems',
      },
      {
        code: 'CO20',
        name: 'Holistic Integration',
        transformation: 'CO',
        definition: 'Unify disparate elements into coherent, seamless whole where boundaries dissolve',
        priority: 4,
        whenToUse: 'For mature system design',
      },
    ],
  },
  DE: {
    code: 'DE',
    name: 'Decomposition',
    description: 'Break complex systems into constituent parts.',
    models: [
      {
        code: 'DE1',
        name: 'Root Cause Analysis (5 Whys)',
        transformation: 'DE',
        definition: 'Iteratively ask why problems occur until fundamental cause emerges',
        priority: 1,
        whenToUse: 'When debugging or problem-solving',
      },
      {
        code: 'DE2',
        name: 'Factorization',
        transformation: 'DE',
        definition: 'Separate multiplicative components to understand relative contribution of each factor',
        priority: 2,
        whenToUse: 'For performance analysis or attribution',
      },
      {
        code: 'DE3',
        name: 'Modularization',
        transformation: 'DE',
        definition: 'Partition system into self-contained units with minimal interdependencies',
        priority: 1,
        whenToUse: 'In software design or organizational structure',
      },
      {
        code: 'DE4',
        name: 'Layered Breakdown',
        transformation: 'DE',
        definition: 'Decompose from system to subsystem to component progressively',
        priority: 2,
        whenToUse: 'For hierarchical analysis',
      },
      {
        code: 'DE5',
        name: 'Dimensional Reduction',
        transformation: 'DE',
        definition: 'Focus on most informative variables while discarding noise or redundancy',
        priority: 3,
        whenToUse: 'For data analysis or simplification',
      },
      {
        code: 'DE6',
        name: 'Taxonomy/Classification',
        transformation: 'DE',
        definition: 'Organize entities into hierarchical categories based on shared properties',
        priority: 2,
        whenToUse: 'For organizing knowledge or products',
      },
      {
        code: 'DE7',
        name: 'Pareto Decomposition (80/20)',
        transformation: 'DE',
        definition: 'Identify vital few drivers producing most impact versus trivial many',
        priority: 1,
        whenToUse: 'For prioritization or focus',
      },
      {
        code: 'DE8',
        name: 'Work Breakdown Structure',
        transformation: 'DE',
        definition: 'Hierarchically divide project into deliverable-oriented components with clear ownership',
        priority: 2,
        whenToUse: 'For project planning',
      },
      {
        code: 'DE9',
        name: 'Signal Separation',
        transformation: 'DE',
        definition: 'Distinguish meaningful patterns from random variation or confounding factors',
        priority: 3,
        whenToUse: 'For data analysis or decision-making',
      },
      {
        code: 'DE10',
        name: 'Abstraction Laddering',
        transformation: 'DE',
        definition: 'Move up and down conceptual hierarchy to find appropriate solution level',
        priority: 3,
        whenToUse: 'For problem reframing',
      },
      {
        code: 'DE11',
        name: 'Scope Delimitation',
        transformation: 'DE',
        definition: 'Define precise boundaries of what is included versus excluded from consideration',
        priority: 2,
        whenToUse: 'At project initiation',
      },
      {
        code: 'DE12',
        name: 'Constraint Isolation',
        transformation: 'DE',
        definition: 'Identify specific limiting factor preventing performance improvement',
        priority: 2,
        whenToUse: 'For bottleneck analysis',
      },
      {
        code: 'DE13',
        name: 'Failure Mode Analysis (FMEA)',
        transformation: 'DE',
        definition: 'Enumerate potential failure points with severity, likelihood, and detectability ratings',
        priority: 3,
        whenToUse: 'For risk management',
      },
      {
        code: 'DE14',
        name: 'Variable Control & Isolation',
        transformation: 'DE',
        definition: 'Hold factors constant to measure single variable\'s causal impact',
        priority: 3,
        whenToUse: 'For experimentation or testing',
      },
      {
        code: 'DE15',
        name: 'Decision Tree Expansion',
        transformation: 'DE',
        definition: 'Map choices and their consequences as branching paths',
        priority: 2,
        whenToUse: 'For decision analysis',
      },
      {
        code: 'DE16',
        name: 'Hypothesis Disaggregation',
        transformation: 'DE',
        definition: 'Break compound claim into testable sub-hypotheses',
        priority: 3,
        whenToUse: 'For scientific inquiry',
      },
      {
        code: 'DE17',
        name: 'Orthogonalization',
        transformation: 'DE',
        definition: 'Ensure factors vary independently without correlation or interdependence',
        priority: 4,
        whenToUse: 'For experimental design',
      },
      {
        code: 'DE18',
        name: 'Scenario Decomposition',
        transformation: 'DE',
        definition: 'Partition future possibilities into discrete, mutually exclusive scenarios',
        priority: 3,
        whenToUse: 'For scenario planning',
      },
      {
        code: 'DE19',
        name: 'Critical Path Unwinding',
        transformation: 'DE',
        definition: 'Trace longest sequence of dependent tasks determining minimum project duration',
        priority: 3,
        whenToUse: 'For project scheduling',
      },
      {
        code: 'DE20',
        name: 'Partition-and-Conquer',
        transformation: 'DE',
        definition: 'Divide problem into independent subproblems solvable separately then combined',
        priority: 2,
        whenToUse: 'For algorithmic problem-solving',
      },
    ],
  },
  RE: {
    code: 'RE',
    name: 'Recursion',
    description: 'Apply operations iteratively, with outputs becoming inputs.',
    models: [
      {
        code: 'RE1',
        name: 'Recursive Improvement (Kaizen)',
        transformation: 'RE',
        definition: 'Continuously refine process through small, frequent enhancements',
        priority: 1,
        whenToUse: 'For continuous improvement',
      },
      {
        code: 'RE2',
        name: 'Feedback Loops',
        transformation: 'RE',
        definition: 'Create mechanisms where system outputs influence future inputs',
        priority: 1,
        whenToUse: 'For adaptive systems',
      },
      {
        code: 'RE3',
        name: 'Meta-Learning (Learn-to-Learn)',
        transformation: 'RE',
        definition: 'Improve the process of learning itself, not just domain knowledge',
        priority: 2,
        whenToUse: 'For skill development or education',
      },
      {
        code: 'RE4',
        name: 'Nested Narratives',
        transformation: 'RE',
        definition: 'Structure information as stories within stories for depth and memorability',
        priority: 4,
        whenToUse: 'For storytelling or communication',
      },
      {
        code: 'RE5',
        name: 'Fractal Reasoning',
        transformation: 'RE',
        definition: 'Recognize self-similar patterns repeating across different scales',
        priority: 3,
        whenToUse: 'For pattern recognition in nature or markets',
      },
      {
        code: 'RE6',
        name: 'Recursive Framing',
        transformation: 'RE',
        definition: 'Apply mental models to the process of selecting mental models',
        priority: 3,
        whenToUse: 'For meta-cognition',
      },
      {
        code: 'RE7',
        name: 'Self-Referential Logic',
        transformation: 'RE',
        definition: 'Create systems that monitor, measure, or modify themselves',
        priority: 3,
        whenToUse: 'For autonomous systems',
      },
      {
        code: 'RE8',
        name: 'Bootstrapping',
        transformation: 'RE',
        definition: 'Build capability using currently available resources, then use that to build more',
        priority: 2,
        whenToUse: 'When starting with minimal resources',
      },
      {
        code: 'RE9',
        name: 'Iterative Prototyping',
        transformation: 'RE',
        definition: 'Cycle rapidly through build-test-learn loops with increasing fidelity',
        priority: 1,
        whenToUse: 'For product development',
      },
      {
        code: 'RE10',
        name: 'Compounding Cycles',
        transformation: 'RE',
        definition: 'Design systems where gains reinforce future gains exponentially',
        priority: 2,
        whenToUse: 'For growth strategies',
      },
      {
        code: 'RE11',
        name: 'Calibration Loops',
        transformation: 'RE',
        definition: 'Repeatedly check predictions against outcomes to improve forecasting accuracy',
        priority: 3,
        whenToUse: 'For improving judgment',
      },
      {
        code: 'RE12',
        name: 'Bayesian Updating in Practice',
        transformation: 'RE',
        definition: 'Continuously revise beliefs as new evidence arrives, weighting by reliability',
        priority: 3,
        whenToUse: 'For decision-making under uncertainty',
      },
      {
        code: 'RE13',
        name: 'Gradient Descent Heuristic',
        transformation: 'RE',
        definition: 'Iteratively adjust toward improvement, even without perfect knowledge of optimal direction',
        priority: 3,
        whenToUse: 'For optimization',
      },
      {
        code: 'RE14',
        name: 'Spiral Learning',
        transformation: 'RE',
        definition: 'Revisit concepts at increasing depth, building on previous understanding',
        priority: 4,
        whenToUse: 'For curriculum design or skill mastery',
      },
      {
        code: 'RE15',
        name: 'Convergence-Divergence Cycling',
        transformation: 'RE',
        definition: 'Alternate between expanding possibilities and narrowing to decisions',
        priority: 2,
        whenToUse: 'For creative problem-solving',
      },
      {
        code: 'RE16',
        name: 'Retrospective→Prospective Loop',
        transformation: 'RE',
        definition: 'Use systematic reflection on past to inform future planning',
        priority: 2,
        whenToUse: 'For learning from experience',
      },
      {
        code: 'RE17',
        name: 'Versioning & Diff',
        transformation: 'RE',
        definition: 'Track changes over time and compare versions to understand evolution',
        priority: 3,
        whenToUse: 'For change management',
      },
      {
        code: 'RE18',
        name: 'Anti-Catastrophic Forgetting',
        transformation: 'RE',
        definition: 'Preserve critical knowledge while adapting to new information',
        priority: 4,
        whenToUse: 'For organizational memory',
      },
      {
        code: 'RE19',
        name: 'Auto-Refactor',
        transformation: 'RE',
        definition: 'Systematically improve system structure without changing external behavior',
        priority: 4,
        whenToUse: 'For technical debt management',
      },
      {
        code: 'RE20',
        name: 'Recursive Governance (Guardrails that Learn)',
        transformation: 'RE',
        definition: 'Establish rules that adapt based on their own effectiveness',
        priority: 5,
        whenToUse: 'For adaptive governance',
      },
    ],
  },
  SY: {
    code: 'SY',
    name: 'Meta-Systems',
    description: 'Understand systems of systems, coordination, and emergent dynamics.',
    models: [
      {
        code: 'SY1',
        name: 'Leverage Points',
        transformation: 'SY',
        definition: 'Identify intervention points where small changes produce disproportionate effects',
        priority: 1,
        whenToUse: 'For strategic intervention',
      },
      {
        code: 'SY2',
        name: 'System Boundaries',
        transformation: 'SY',
        definition: 'Define what is inside versus outside system scope for analysis or design',
        priority: 1,
        whenToUse: 'At start of systems analysis',
      },
      {
        code: 'SY3',
        name: 'Stocks & Flows',
        transformation: 'SY',
        definition: 'Distinguish accumulations from rates of change affecting them',
        priority: 2,
        whenToUse: 'For systems modeling',
      },
      {
        code: 'SY4',
        name: 'Requisite Variety',
        transformation: 'SY',
        definition: 'Match control system\'s complexity to system being controlled',
        priority: 3,
        whenToUse: 'For governance design',
      },
      {
        code: 'SY5',
        name: 'Systems Archetypes',
        transformation: 'SY',
        definition: 'Recognize recurring dynamic patterns across different domains',
        priority: 2,
        whenToUse: 'For pattern matching in systems',
      },
      {
        code: 'SY6',
        name: 'Feedback Structure Mapping',
        transformation: 'SY',
        definition: 'Diagram causal loops showing how variables influence each other',
        priority: 2,
        whenToUse: 'For understanding system dynamics',
      },
      {
        code: 'SY7',
        name: 'Path Dependence',
        transformation: 'SY',
        definition: 'Acknowledge how early decisions constrain future options through accumulated consequences',
        priority: 2,
        whenToUse: 'For strategic planning',
      },
      {
        code: 'SY8',
        name: 'Homeostasis/Dynamic Equilibrium',
        transformation: 'SY',
        definition: 'Understand self-regulating mechanisms maintaining stable states despite disturbances',
        priority: 3,
        whenToUse: 'For stability analysis',
      },
      {
        code: 'SY9',
        name: 'Phase Transitions & Tipping Points',
        transformation: 'SY',
        definition: 'Identify thresholds where gradual changes produce sudden qualitative shifts',
        priority: 2,
        whenToUse: 'For monitoring critical changes',
      },
      {
        code: 'SY10',
        name: 'Causal Loop Diagrams',
        transformation: 'SY',
        definition: 'Visualize circular cause-effect relationships with reinforcing and balancing dynamics',
        priority: 3,
        whenToUse: 'For systems thinking',
      },
      {
        code: 'SY11',
        name: 'Governance Patterns',
        transformation: 'SY',
        definition: 'Design decision rights, accountability structures, and coordination mechanisms',
        priority: 2,
        whenToUse: 'For organizational design',
      },
      {
        code: 'SY12',
        name: 'Protocol/Interface Standards',
        transformation: 'SY',
        definition: 'Specify rules for interaction enabling coordination without central control',
        priority: 3,
        whenToUse: 'For decentralized systems',
      },
      {
        code: 'SY13',
        name: 'Incentive Architecture',
        transformation: 'SY',
        definition: 'Design reward and penalty structures aligning individual actions with system goals',
        priority: 2,
        whenToUse: 'For behavior design',
      },
      {
        code: 'SY14',
        name: 'Risk & Resilience Engineering',
        transformation: 'SY',
        definition: 'Build systems that fail gracefully and recover automatically',
        priority: 2,
        whenToUse: 'For reliability engineering',
      },
      {
        code: 'SY15',
        name: 'Multi-Scale Alignment',
        transformation: 'SY',
        definition: 'Ensure strategy, operations, and execution cohere across organizational levels',
        priority: 3,
        whenToUse: 'For organizational coherence',
      },
      {
        code: 'SY16',
        name: 'Ecosystem Strategy',
        transformation: 'SY',
        definition: 'Position organization within network of partners, competitors, and stakeholders',
        priority: 3,
        whenToUse: 'For competitive strategy',
      },
      {
        code: 'SY17',
        name: 'Policy Feedbacks',
        transformation: 'SY',
        definition: 'Anticipate how rules shape behavior, which creates conditions affecting future rules',
        priority: 4,
        whenToUse: 'For policy design',
      },
      {
        code: 'SY18',
        name: 'Measurement & Telemetry',
        transformation: 'SY',
        definition: 'Instrument systems to capture state, changes, and anomalies for informed response',
        priority: 2,
        whenToUse: 'For system monitoring',
      },
      {
        code: 'SY19',
        name: 'Meta-Model Selection',
        transformation: 'SY',
        definition: 'Choose appropriate framework or tool for specific problem characteristics',
        priority: 1,
        whenToUse: 'When selecting mental models',
      },
      {
        code: 'SY20',
        name: 'Systems-of-Systems Coordination',
        transformation: 'SY',
        definition: 'Manage interactions between independent systems with emergent behaviors',
        priority: 3,
        whenToUse: 'For complex system orchestration',
      },
    ],
  },
};
